services:
  postgres:
    restart: unless-stopped
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: thallium
      POSTGRES_PASSWORD: thallium
      POSTGRES_USER: thallium
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U thallium"]
      interval: 2s
      timeout: 1s
      retries: 5
    ports:
      - "15432:5432"

  thallium:
    build: thallium-backend
    restart: unless-stopped
    command: ["alembic upgrade head && uvicorn src.app:fastapi_app --host 0.0.0.0 --port 8000 --reload"]
    volumes:
      - ./thallium-backend/src:/thallium/src:ro
    env_file:
      - .env
    environment:
      BACKEND_DATABASE_URL: postgresql+psycopg_async://thallium:thallium@postgres:5432/thallium
      BACKEND_TOKEN: suitable-for-development-only
    ports:
      - "8000:80"
    depends_on:
      postgres:
        condition: service_healthy
