"""
Make colours nullable and add colour_code2.

Revision ID: d74a6956b012
Revises: 8c35ad6bab78
Create Date: 2024-08-25 01:42:04.001456+00:00
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d74a6956b012"
down_revision = "8c35ad6bab78"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("variants", sa.Column("colour_code2", sa.String(), nullable=True))
    op.alter_column("variants", "colour", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("variants", "colour_code", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("variants", "colour_code", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("variants", "colour", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("variants", "colour_code2")
    # ### end Alembic commands ###
