"""
Replace products with templates and variants.

Revision ID: 8c35ad6bab78
Revises: bd897d0f21e1
Create Date: 2024-08-24 23:03:01.084903+00:00
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8c35ad6bab78"
down_revision = "bd897d0f21e1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "templates",
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("mockup_file_url", sa.String(), nullable=False),
        sa.Column("last_synced", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("template_id", name=op.f("templates_pk")),
    )
    op.create_table(
        "variants",
        sa.Column("variant_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("size", sa.String(), nullable=False),
        sa.Column("colour", sa.String(), nullable=False),
        sa.Column("colour_code", sa.String(), nullable=False),
        sa.Column("price", sa.Numeric(), nullable=False),
        sa.Column("last_synced", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("variant_id", name=op.f("variants_pk")),
    )
    op.create_table(
        "template_variant",
        sa.Column("template_id", sa.Integer(), nullable=True),
        sa.Column("variant_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["templates.template_id"],
            name=op.f("template_variant_template_id_templates_fk"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["variants.variant_id"],
            name=op.f("template_variant_variant_id_variants_fk"),
            ondelete="CASCADE",
        ),
    )
    op.drop_table("products")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("product_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("price", sa.NUMERIC(), autoincrement=False, nullable=False),
        sa.Column("image", postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("product_id", "id", name="products_pk"),
    )
    op.drop_table("template_variant")
    op.drop_table("variants")
    op.drop_table("templates")
    # ### end Alembic commands ###
