on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python Dependencies
        uses: HassanAbouelela/actions/setup-python@setup-python_v1.4.2
        with:
          python_version: "3.12"
          install_args: "--only linting"

      - name: Ensure requirements.txt is up to date
        shell: bash
        run: |
          poetry export --output temp-requirements.txt -vvv

          if ! cmp -s "requirements.txt" "temp-requirements.txt"; then
            echo "::error file=requirements.txt,title=Requirements out of date!::Run 'poetry export --output requirements.txt'"
            exit 1
          fi

      - name: Run pre-commit hooks
        run: SKIP=ruff-lint pre-commit run --all-files

      # Run `ruff` using github formatting to enable automatic inline annotations.
      - name: Run ruff
        run: "ruff check --output-format=github ."
