name: main

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          automation: &automation
            - '.github/workflows/**'
            - 'deployments/**'
          backend:
            - *automation
            - 'thallium-backend/**'

  generate-inputs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    outputs:
      sha-tag: ${{ steps.sha-tag.outputs.sha-tag }}
    steps:
      - name: Create SHA Container Tag
        id: sha-tag
        run: |
          tag=$(cut -c 1-7 <<< $GITHUB_SHA)
          echo "sha-tag=$tag" >> $GITHUB_OUTPUT

  lint-backend:
    uses: ./.github/workflows/lint-backend.yaml

  lint-frontend:
    uses: ./.github/workflows/lint-frontend.yaml

  build-backend:
    if: ${{ needs.changes.outputs.backend == 'true' }}
    needs: [changes, generate-inputs, lint-backend]
    uses: ./.github/workflows/build-deploy.yaml
    with:
      sha-tag: ${{ needs.generate-inputs.outputs.sha-tag }}
      project: backend
    secrets: inherit
